clinet/urls.py
from django.urls import path
from clinet import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.dashboard_login, name="login"),
    path('logout/', views.dashboard_logout, name="logout"),
    path('category_list/', views.category_list, name="category_list"),
    path('category_create/', views.category_create, name="category_create"),
    path('<int:pk>category_edit/', views.category_edit, name="category_edit"),
    path('<int:pk>/category_delete/', views.category_delete, name="category_delete"),
    path('product_list/', views.product_list, name="product_list"),
    path('product_create/', views.product_create, name="product_create"),
    path('<int:pk>product_edit/', views.product_edit, name="product_edit"),
    path('<int:pk>/product_delete/', views.product_delete, name="product_delete"),
    path('kontak_create/', views.kontak_create, name="kontak_create"),
    path('kontak_list/', views.kontak_list, name='kontak_list' ),
    path('<int:pk>/kontak_edit/', views.kontak_edit, name="kontak_edit"),
    path('<int:pk>/kontak_delete/', views.kontak_delete, name="kontak_delete"),


]

main/urls.py
from django.urls import path,include
from .views import home, Menu, About, Con, Pro


app_name = "main"

urlpatterns = [
    path("", home, name="index"),
    path("menu/", Menu.as_view(), name="menu"),
    # path("gallery/", Pro.as_view(), name="gallery"),
    path("about/", About.as_view(), name="about"),
    path("con/", Con.as_view(), name="con"),
    path('dashboard/', include('clinet.urls'))

]

well/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
# from django.contrib import admin
# from django.urls import path, include
#
#
# urlpatterns = [
#     # path('admin/', admin.site.urls),
#     path("", include("main.urls")),
# ]
#
#
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('main.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/dashboard/kontak/form.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Kontak</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Saytga oʻtish</a></li>
          <li class="breadcrumb-item active">Kontak</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
            <div class="card card-primary">

              <form method="post"  >
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Adress</label>
                      {{form.name}}
                  </div>
                </div>
                  <div class="card-body">
                  <div class="form-group">
                    <label>Kontak nomer</label>
                      {{form.nomber}}
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Saqlash</button>
                </div>
              </form>
            </div>

          </div>
        </div>
    </div>
</section>
{% endblock %}

templates/dashboard/kontak/list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Kontak</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Saytga oʻtish</a></li>
                        <li class="breadcrumb-item active">Kontak</li>
                    </ol>
                </div>
            </div>

        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">

                            <div class="card-tools">
                                <a href="{% url 'main:kontak_create' %}">
                                    <div class="btn btn-block btn-outline-success">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                            <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
                                        </svg>
                                        Qoʻshish
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Kontak nomi</th>
                                    <th>Nomer</th>
                                    <th>Taxrirlash</th>
                                    <th>Oʻchrish</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for i in kontak %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ i.name }}</td>
                                        <td>{{ i.nomber }}</td>
                                        <td><a href="{% url 'main:kontak_edit' pk=i.id %}">
                                            <div class=" m-6 btn btn-block btn-outline-warning">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-pencil-square"
                                                     viewBox="0 0 16 16">
                                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                    <path fill-rule="evenodd"
                                                          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                </svg>
                                                Taxrirlash
                                            </div>
                                        </a></td>
                                        <td><a href="{% url 'main:kontak_delete' pk=i.id %}">
                                            <div class="m-6 btn btn-block btn-outline-danger ">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd"
                                                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg>
                                                Oʻchrish
                                            </div>
                                        </a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
{% endblock %}